from fastapi import APIRouter, Depends

from apps.api.dependencies import services

router = APIRouter(tags=["system"])


@router.get("/health")
def health(svc=Depends(services)):
    return {
        "status": "ok",
        "mode": svc.settings.mode,
        "version": "0.2.0",
        "retrieval": "hybrid" if svc.retriever.vector else "bm25",
        "reranker": bool(svc.retriever.reranker),
        "voice": {"stt": bool(svc.settings.stt_path), "tts": bool(svc.settings.tts_model)},
        "auth_required": bool(svc.settings.api_key),
    }


@router.get("/health/model")
def model(svc=Depends(services)):
    return {"model": svc.settings.model, **svc.agent.llm.health()}


@router.get("/activity")
def activity(svc=Depends(services)):
    return svc.store.rows("SELECT * FROM audit_events ORDER BY id DESC LIMIT 200")


@router.get("/metrics")
def metrics(svc=Depends(services)):
    return {
        name: svc.store.rows("SELECT COUNT(*) AS count FROM " + table)[0]["count"]
        for name, table in [
            ("documents", "knowledge"),
            ("datasets", "datasets"),
            ("conversations", "conversations"),
            ("tasks", "tasks"),
            ("audit_events", "audit_events"),
        ]
    }


@router.get("/evaluations")
def evaluations():
    # Results are generated by scripts/run_evaluation.py, never fabricated at runtime.
    return {
        "status": "run_locally",
        "command": "python scripts/run_evaluation.py",
        "report": "docs/validation.md",
    }
